osqp/osqp

include/glob_opts.h

This change is important for my unit tests. I tested it out on my machine.

fixed printing in python

---

CMakeLists.txt

Revert "R2018a compatibility"

---

README.md

Updated badges. Added download stats badges.

Updated and added more badges

---

docs/_static/css/osqp_theme.css

Added also small fix for google fonts.

Change background of docs examples

---

docs/interfaces/julia.rst
docs/interfaces/matlab.rst
docs/interfaces/python.rst
include/types.h
src/kkt.c
src/osqp.c
src/util.c

Added `update_time` to the info structure. It measure the time spent on updating the problem data.
Fixes https://github.com/oxfordcontrol/osqp/issues/101

Add update_time to the info structure

---

.bumpversion.cfg
CHANGELOG.md
README.md
ci/appveyor/deploy.cmd
ci/travis/deploy.sh
docs/conf.py
docs/doxygen.conf
docs/get_started/CC++.rst
docs/get_started/matlab.rst
include/constants.h
lin_sys/direct/pardiso/pardiso_interface.c
lin_sys/direct/qdldl/qdldl_interface.c

Checking that everything runs before tagging the release.

Release 0.5.0

---

include/auxil.h
include/cs.h
include/ctrlc.h
include/lin_alg.h
include/polish.h
include/types.h
include/util.h
src/auxil.c
src/cs.c
src/osqp.c
src/scaling.c

Correct some typos in code comments.

Correct spelling in code comments

---

include/osqp.h
src/osqp.c

Fixes https://github.com/oxfordcontrol/osqp/issues/127

Fixed docs in functions that update matrices

---

ci/appveyor/script.cmd
ci/travis/script.sh
include/auxil.h
lin_sys/lib_handler.c
src/auxil.c
src/osqp.c
src/util.c
tests/non_cvx/test_non_cvx.h

Fixed printing disabled

---

tests/basic_qp/test_basic_qp.h
tests/basic_qp2/test_basic_qp2.h
tests/lin_alg/test_lin_alg.h
tests/minunit.h
tests/non_cvx/test_non_cvx.h
tests/osqp_tester.c
tests/primal_dual_infeasibility/test_primal_dual_infeasibility.h
tests/primal_infeasibility/test_primal_infeasibility.h
tests/solve_linsys/test_solve_linsys.h
tests/unconstrained/test_unconstrained.h
tests/update_matrices/test_update_matrices.h
tests/utils/codegen_utils.py

- Added casts from (void*) to desired types.
- Changed char* to const char*.
- Added function prototypes to the codegen_utils.py script.
This change is helpful for clients that need to implement OSQP integration tests from C++ unit testing frameworks.

Updated tests to be C++ compliant

---

docs/get_started/julia.rst
docs/get_started/linear_system_solvers.rst

Minor edits docs

---

src/auxil.c

Since `delta_y` needs to be in the polar of the recession cone of `[l,u]`, we now check the primal infeasibility conditions with the vector obtained by projecting `delta_y` onto that cone.
Fixes https://github.com/oxfordcontrol/osqp/issues/144

Fix primal infeasibility check

---

docs/_static/css/osqp_theme.css
docs/index.rst
docs/parsers/jump.rst
docs/parsers/yalmip.rst

Fix paragraphs too messy with new docs

Updated style docs

---

docs/citing/index.rst

Added volume, issue, and page numbers.

Updated JOTA paper

---

.bumpversion.cfg
CHANGELOG.md
README.md
ci/travis/script.sh
docs/_static/css/osqp_theme.css
docs/citing/index.rst
docs/examples/setup-and-solve.rst
docs/examples/update-matrices.rst
docs/examples/update-vectors.rst
docs/get_started/CC++.rst
docs/get_started/linear_system_solvers.rst
docs/get_started/python.rst
docs/index.rst
docs/parsers/jump.rst
docs/parsers/yalmip.rst
docs/solver/index.rst
include/glob_opts.h
include/osqp_api_constants.h
lin_sys/direct/qdldl/qdldl_interface.c
src/auxil.c
src/util.c

This required a manual merge locally, so this PR is mainly to make sure CI passes after doing that.

Pull changes from 0.6 into 1.0 development branch

---

include/glob_opts.h
lin_sys/direct/qdldl/amd/include/SuiteSparse_config.h
lin_sys/direct/qdldl/amd/src/SuiteSparse_config.c
src/util.c

Fixes https://github.com/oxfordcontrol/osqp-python/issues/33 
- It releases GIL when printing
- It uses raw python memory management functions that do no require GIL

Fix segfault when using multithreaded single-shot function in python

---

ci/travis/install.sh
docs/interfaces/eigen.rst
docs/interfaces/index.rst
docs/interfaces/rlang.rst
docs/interfaces/ruby.rst

- Divided interfaces between `official` and `community maintained`. 
- Added Ruby interface. Fixes #223.

Updated interfaces in documentation

---

docs/citing/index.rst

I noticed when needing to cite the main OSQP paper that the website citation didn't have the updated journal citation.

Update main paper citation

---

docs/_static/css/osqp_theme.css
docs/citing/index.rst
docs/codegen/matlab.rst
docs/codegen/python.rst
docs/interfaces/CC++.rst
docs/interfaces/eigen.rst
docs/interfaces/eigen_google.rst
docs/interfaces/eigen_robotology.rst
docs/interfaces/index.rst
docs/interfaces/linear_systems_solvers.rst
docs/interfaces/matlab.rst
docs/interfaces/python.rst
docs/interfaces/solver_settings.rst

Added links to new C++ interface by Google @mlubin @gbanjac.

Added references to Google C++ interface

---

docs/interfaces/eigen_google.rst
docs/interfaces/eigen_robotology.rst

Resolve PR comment https://github.com/oxfordcontrol/osqp/pull/265#discussion_r467506342

Minor edit docs

---

.bumpversion.cfg
.travis.yml
CHANGELOG.md
LICENSE
README.md
appveyor.yml
ci/appveyor/deploy.cmd
docs/conf.py
docs/doxygen.conf
docs/get_started/CC++.rst
docs/get_started/matlab.rst
docs/get_started/python.rst
include/constants.h
src/auxil.c
src/osqp.c
src/util.c
tests/basic_qp/test_basic_qp.h
tests/custom_memory/custom_memory.c

Release 0.6.2 from branch`develop-0.x`. Needed for Python 3.9
Fixes #271

Release 0.6.2

---

site/_pages/citing.md

PR 332 Suggestions

---

.github/workflows/main.yml

Fixes https://github.com/osqp/osqp/issues/360

Update the list of excluded files from coverage

---

.github/workflows/docs.yml

Change parallel to PR #472, but this time towards `develop-1.0`

building both master/develop-1.0 docs

---

.github/workflows/mkl.yaml

Trying to fix ongoing mkl installation issue on windows-2022

trying latest mkl-devel

---

algebra/_common/csc_math.h
algebra/_common/csc_utils.h
algebra/_common/kkt.h
algebra/_common/lin_sys/qdldl/qdldl_interface.h
algebra/_common/reduced_kkt.h
algebra/builtin/algebra_impl.h
algebra/mkl/algebra_impl.h
algebra/mkl/blas_helpers.h
include/private/algebra_matrix.h
include/private/algebra_vector.h
include/private/auxil.h
include/private/codegen.h
include/private/derivative.h
include/private/error.h
include/private/glob_opts.h
include/private/interrupt.h
include/private/lin_alg.h
include/private/polish.h
include/private/printing.h
include/private/scaling.h
include/private/timing.h
include/private/types.h
include/private/util.h
tests/lin_alg/test_lin_alg.h
tests/osqp_api.h
tests/update_matrices/test_update_matrices.cpp
tests/utils/test_utils.cpp

* Make every include be C linkage by default
* Minor formatting fixes

Fixup include files

---

docs/contributing/index.rst
docs/contributing/python.rst
docs/contributing/solvers.rst

Contributing section for python. Not perfect, but gives us a place to start adding more detailed stuff.

Contributing section for python wrappers

---

CMakeLists.txt

WIP to allow `scikit-build` as a backend for `osqp-python`.

Specify codegen install location in CMake variable

---

.pre-commit-config.yaml

Update pre-commit-hooks lib

---

docs/examples/huber.rst
docs/examples/lasso.rst
docs/examples/least-squares.rst
docs/examples/mpc.rst
docs/examples/portfolio.rst
docs/examples/setup-and-solve.rst
docs/examples/svm.rst
docs/examples/update-matrices.rst
docs/examples/update-vectors.rst

Fixing all examples in documentation

updated examples (except Matlab)

---

.github/workflows/release.yml
include/private/version.h

:tada: Version 1.0.0 release :tada:

Bump to version 1.0.0

---

docs/contributing/python.rst
docs/get_started/python.rst
docs/interfaces/python.rst

Added a line about the optional parameter `raise_errors` as it currently exists in the python wrapper.

Added bit about raise_errors in for solve method
