osqp/osqp

.gitignore
CHANGELOG.md
CMakeLists.txt
configure/cmake/cmake_uninstall.cmake.in
docs/installation/CC++.rst
docs/installation/sources.rst
lin_sys/direct/CMakeLists.txt

These modifications simplify the installation of the library using CMake and the consumption of the library from CMake downstream projects.
In particular, if the default installation prefix is used then the library can be easily used in downstream project as: 
~~~
find_package(osqp REQUIRED)
target_link_libraries(yourTarget PRIVATE osqp::osqp)
target_link_libraries(yourTarget PRIVATE osqp::osqpstatic)
~~~
See https://cmake.org/cmake/help/v3.2/command/find_package.html#command:find_package and https://cmake.org/cmake/help/v3.2/manual/cmake-packages.7.html for more information about CMake config packages. 
I would be happy to document this somewhere, but the only existing instructions for C/C++ are the one in https://github.com/oxfordcontrol/osqp/blob/17809ff56b3b9e5cefc7fa63514c47ca6d928d83 …

Add installation and exporting of CMake targets

---

lin_sys/direct/suitesparse/suitesparse_ldl.c

Resolves #44 
Now Valgrind is happy
```
-----------------------------------------------------------------
OSQP v0.2.1  -  Operator Splitting QP Solver
(c) Bartolomeo Stellato,  Goran Banjac
University of Oxford  -  Stanford University 2017
-----------------------------------------------------------------
problem:  variables n = 3, constraints m = 7
nnz(P) + nnz(A) = 20
settings: linear system solver = suitesparse ldl,
eps_abs = 1.0e-03, eps_rel = 1.0e-03,
eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
rho = 1.00e-01 (adaptive)
sigma = 1.00e-06, alpha = 1.60, max_iter = 4000
check_termination: on (interval 25)
scaling: on, scaled_termination: off
warm start: on, polish: on
iter   objective    pri res    dua res    rho        time
1   0.0000e+00   1.00e+00   1.00e+02   1.00e-01   8.16e-02s …
```

remove KKT_temp when LDL fails.

---

lin_sys/direct/suitesparse/suitesparse_ldl.c

Resolves #47 
As Bodono points out in https://github.com/cvxgrp/scs/issues/94#issuecomment-365322333, `LDLSolve` in `SCS` is already `static`. Making `LDLSolve` also static in `OSQP` will resolve the name conflict.

Make LDLSolve static.

---

src/osqp.c

I got a warning when I compile `osqp`, complaining that `can_print` might be uninitialized.
```external/osqp/include/osqp.h: In function 'osqp_solve':
external/osqp/src/osqp.c:410:5: warning: 'can_print' may be used uninitialized in this function [-Wmaybe-uninitialized]
if(!can_print){
^
external/osqp/src/osqp.c:228:8: note: 'can_print' was declared here
c_int can_print; // Boolean whether you can print
```
This was on an old version of OSQP, so the line number do not match exactly.

initialize can_print

---

lin_sys/direct/suitesparse/suitesparse_ldl.c
src/util.c

These simple fixes will enable this code to be compiled with Visual Studio 2008, which should simplify the building of a Python 2.7 module considerably. 
See https://github.com/oxfordcontrol/osqp-python/pull/6

Enable compilation with VS 2008 for Python 2.7

---

include/ctrlc.h
include/util.h
src/auxil.c
src/ctrlc.c
src/osqp.c
src/polish.c
src/util.c

Avoids naming conflicts with ECOS.
See #72 and #67.
I added `static` to the unix version of `handle_ctrlc` because it's internal to ctrlc.c. I'm not confident enough to touch the windows version and also can't test that it works locally.

Namespace interrupt functions and tic/toc

---

CMakeLists.txt

It seems that ctrlc.c is being compiled even when the flag CTRLC is OFF. Any particular reason as to why?
I just added a quick check to see if CTRLC is OFF and removed ctrlc.c/h from source/include files accordingly...

Remove ctrlc.c from sources when CTRLC is OFF

---

docs/codegen/matlab.rst
docs/codegen/python.rst

I added new arguments in the `codegen` method both in Matlab and Python. They allow setting `DFLOAT` and `DLONG` flags in `emosqp` interfaces.
Matlab (master branch): https://github.com/oxfordcontrol/osqp-matlab/commit/d76478cae0623f0d2d9da939f4009f7fc9a71318
Python (develop branch): https://github.com/oxfordcontrol/osqp-python/commit/d0ef645d5fd6abd2c9b6368b15f28a6045179219

Updated docs to reflect new arguments in codegen method

---

.editorconfig
.valgrind-suppress.supp
CHANGELOG.md
CMakeLists.txt
ci/travis/script.sh
configure/osqp_configure.h.in
docs/examples/update-matrices.rst
docs/examples/update-vectors.rst
examples/osqp_demo.c
include/glob_opts.h
src/auxil.c
src/osqp.c
src/util.c
tests/basic_qp/test_basic_qp.h
tests/custom_memory/custom_memory.c
tests/custom_memory/custom_memory.h
tests/osqp_tester.c

This PR adds the possibility to pass custom memory management functions. It can be done by specifying an additional header file where the custom functions are defined (or included) as `-DOSQSP_CUSTOM_MEMORY_H=myfile.h`
The file should have the structure
```c
```
@nikalra does it solve your issue? #136. Feedbacks are welcome.

Custom memory allocators

---

CHANGELOG.md
docs/contributing/index.rst
docs/get_started/julia.rst
docs/get_started/linear_system_solvers.rst
include/types.h
lin_sys/direct/pardiso/pardiso_interface.c
lin_sys/direct/pardiso/pardiso_interface.h
lin_sys/direct/qdldl/qdldl_interface.c
lin_sys/direct/qdldl/qdldl_interface.h
src/auxil.c
src/osqp.c
src/polish.c
tests/basic_qp/test_basic_qp.h
tests/solve_linsys/generate_problem.py
tests/solve_linsys/test_solve_linsys.h

The main change is that `linsys_solver->solve` function now computes the vector `(x_tilde,z_tilde)` instead of `(x_tilde,nu)` (in the non-polishing mode). OSQP should be agnostic to `nu` since indirect solvers do not need this vector.
I have also removed unused arguments of linsys solver functions.

Change interface of linsys solver functions

---

docs/examples/huber.rst
docs/examples/lasso.rst
docs/examples/least-squares.rst
docs/examples/mpc.rst
docs/examples/portfolio.rst
docs/examples/svm.rst
include/constants.h
include/types.h
src/auxil.c
src/util.c
tests/basic_qp/generate_problem.py
tests/basic_qp/test_basic_qp.h
tests/basic_qp2/generate_problem.py
tests/demo/CMakeLists.txt
tests/demo/test_demo.h
tests/lin_alg/generate_problem.py
tests/non_cvx/generate_problem.py
tests/osqp_tester.c
tests/primal_dual_infeasibility/generate_problem.py
tests/primal_infeasibility/generate_problem.py
tests/solve_linsys/generate_problem.py
tests/unconstrained/generate_problem.py
tests/update_matrices/generate_problem.py
tests/update_matrices/test_update_matrices.h

- Coverage increased by 4%
- Fixed docs in `types.h` (when a comment is broken in more than one line, only first line is shown on the documentation website - see e.g. [here](https://osqp.org/docs/interfaces/cc++#_CPPv4N12OSQPSettings7scalingE))
- Fixed printing of polishing info in Python on Windows

Add more unit tests to improve coverage

---

include/error.h

The C99 standard defines the __func__ macro for the function name, so that should be the preferred macro to use for C99 and later. This makes it a conditional define that uses __func__ if it is C99 or later, and __FUNCTION__ for the other cases (which will be compiler dependent).
This isn't actually an error when using C99 and GCC, but it triggers a warning that gets annoying.

Make error macro C99 friendly

---

lin_sys/direct/qdldl/qdldl_interface.c
src/osqp.c

This set of commits fixes 3 main things:
* The error checking functions never actually returned from the function, so it was still possible to segfault on the main interface routines.
* The ```osqp_cleanup``` function referenced the settings struct without checking for NULL, even though it was checked before freeing it.
* There was the possibility of a small memory leak in the qdldl interface on an error.

Fix some memory errors

---

CMakeLists.txt
ci/travis/script.sh
include/CMakeLists.txt
src/CMakeLists.txt
src/osqp.c
tests/basic_qp/test_basic_qp.h

The main portion of the PR is to clean up the CMake list creation so it can simplify the upkeep of the CMake for the code generation routines. This moves the list creation into a CMakeLists inside the src and include folders, so now in code generation frameworks the main CMakeLists should just add these directories instead of having to keep a separate list of the files (which can become out of date as changes are made).
Additionally, the first commit fixes a build error that was introduced recently in embedded mode, and the last commit adds building of the embedded code to the Travis script so that any changes that might break embedded compilation will be caught in CI.

CMake updates for embedded code generation

---

include/CMakeLists.txt
include/lin_sys.h
src/CMakeLists.txt
src/lin_sys.c

These files were completely ignored for embedded mode (#ifndef wrapped) but were still included in the CMake list of source files. This now has CMake ignore them, so the #ifndef is no longer needed.

Have CMake handle conditional compilation of lin_sys.c/h

---

docs/get_started/python.rst

Main anaconda packaging is now done in conda-forge. This PR updates the docs accordingly. It also removes tricky dev deployments for now.

Updated python docs to use conda-forge

---

lin_sys/direct/qdldl/qdldl_interface.c

Adds more detailed informational messages when `QDLDL_etree` returns an error code.    This is for compatibility with https://github.com/oxfordcontrol/qdldl/pull/25.
Note that I have not yet updated the qdldl submodule target.   I will do so when we tag a v.0.1.4 release for QDLDL for the above fix.

update LDL etree error handling

---

lin_sys/direct/qdldl/qdldl_interface.c

The L matrix nzmax was not being set, so code generation resulted in a garbage value. This value is not used anywhere in the code though, so it doesn't seem to have had an observable effect on the solver.
Fixes oxfordcontrol/osqp-matlab#20

Set nzmax for qdldl L matrix

---

include/glob_opts.h

Adds preprocessor logic to allow for interface-specific definitions of `c_eprint`.
The behaviour is unchanged except when `R_LANG` is defined. In the case of `R_LANG`, `c_eprint` is define directly as the R native print function, avoiding usage of `__FUNCTION__` and `__VA_ARGS__`. These cause difficulties with CRAN warnings on some platforms which insist on building with `-Wpedantic`, specifically the fedora CRAN test server.

interface-specific c_eprint config

---

src/auxil.c

We were never verifying that q, u, and l were actually passed into the solver before being accessed, so we would get segmentation faults. This updates the `validate_data` function to test for if these three are null.
Fixes #214

Verify that q, u, and l are not null

---

include/types.h

A quick documentation fix that should propagate through doxygen to the .rst documentation files.

Documentation fix in the OSQPWorkspace struct.

---

CMakeLists.txt

I found a some files that went into /usr/lib when building on 64-bit architectures
I think that if I build for 64-bit, it should go to /usr/lib64 with this changes.

Update CMakeLists.txt to use correct library directory under linux.

---

.github/workflows/build_docs.sh
.github/workflows/main.yml
README.md
docs/conf.py

All steps I found in the old shell scripts for Travis/Appveyor seem to work fine with this setup, on all 3 platforms.
I'm using a matrix of cmake flags across all platforms, but certain steps (valgrind/coveralls etc.) are only performed only on certain matrix values of the variables.
- Build
- Test (if `-DUNITTESTS=ON -DCOVERAGE=ON` in the build step).
- Valgrind/Coveralls in the case when using Linux + base cmake case with `-DUNITTESTS=ON -DCOVERAGE=ON`
- Building Sphinx Docs
For the last step, the `.html` pages are deployed in a branch called `gh-pages`. To integrate this with Github pages, someone in charge of the repo would have to go to 'Settings -> Github Pages -> Source -> select `gh-pages` as the branch, with `/` as the folder. The live site (minus the current landing pages which …

Github actions

---

CITATION.cff

GitHub has recently added the ability for the sidebar of the main repo to display information about how to cite a repository and its software. They use the CFF (citation file format) as their basis (although they did add bibtex support, but it isn't as featured), so we need to add a CITATION.cff file to use this. This format allows for specifying the preferred thing to cite, so we can specify the published paper as what people should cite.
More information about this: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files and https://twitter.com/natfriedman/status/1420122675813441540?s=20

Initial citation file to use GitHub's built-in citation tool

---

.gitmodules
CHANGELOG.md
README.md
docs/citing/index.rst
docs/contributing/index.rst
docs/get_started/CC++.rst
docs/get_started/julia.rst
docs/get_started/linear_system_solvers.rst
docs/get_started/matlab.rst
docs/get_started/python.rst
docs/get_started/r.rst
docs/get_started/sources.rst
docs/index.rst
docs/interfaces/fortran.rst
docs/interfaces/index.rst
docs/interfaces/status_values.rst
site/_config.yml
site/_layouts/home.html
site/_pages/citing.md

Replaced all instances of `github.com/oxfordcontrol/` with `github.com/osqp/`. All links do work, so perhaps the organization was renamed at some point?
Also replaced references to Bintray with Github Releases.

Replaced oxfordcontrol/Bintray references

---

docs/conf.py
docs/doxygen.conf
site/_pages/citing.md

Removed hardcoded `0.6.2` from doxygen configuration. The version number is now obtained from an environment variable passed down from Sphinx. A blank version number is used for sphix+doxygen purposes in case it is 0.0.0.
Doxygen html generation is not needed for integration with Sphinx - just xml, so its now disabled by default.

Dynamic doxygen project version

---

algebra/_common/csc_math.c
algebra/_common/csc_math.h
algebra/cuda/algebra_types.h
algebra/cuda/include/csr_type.h
algebra/cuda/include/cuda_handler.h
algebra/cuda/include/cuda_lin_alg.h
algebra/cuda/lin_sys/indirect/cuda_pcg.cu
algebra/cuda/lin_sys/indirect/cuda_pcg_interface.c
algebra/cuda/lin_sys/indirect/cuda_pcg_interface.h
algebra/cuda/matrix.cu
algebra/cuda/src/cuda_csr.cu
algebra/cuda/src/cuda_lin_alg.cu
algebra/cuda/vector.cu
algebra/default/algebra_impl.h
algebra/default/matrix.c
algebra/mkl/algebra_impl.h
algebra/mkl/matrix.c
include/algebra_matrix.h
include/algebra_vector.h
src/auxil.c
tests/lin_alg/test_lin_alg.h
tests/osqp_tester.cpp

I have also removed `OSQPMatrix_quad_form()` as there is no need for it. We always evaluate the objective function after computing the dual residual `Px + q + A'y`, which means that `Px` is already computed; hence, we can evaluate the inner product between `Px` and `x` instead of computing `x'Px` from scratch.

Replace deprecated cusparse functions by cusparseSpMV()

---

CMakeLists.txt

Adds an information line reporting the final status of the CTRLC option in cmake.   This would have been helpful with #366, for example.

report CNTRLC status

---

.github/workflows/main.yml
algebra/cuda/lin_sys/indirect/cuda_pcg_interface.cu
algebra/cuda/lin_sys/indirect/cuda_pcg_interface.h
algebra/default/lin_sys/direct/qdldl_interface.c
algebra/default/lin_sys/direct/qdldl_interface.h
algebra/mkl/lin_sys/direct/pardiso_interface.c
algebra/mkl/lin_sys/direct/pardiso_interface.h
algebra/mkl/lin_sys/indirect/mkl-cg_interface.c
algebra/mkl/lin_sys/indirect/mkl-cg_interface.h
docs/contributing/index.rst
include/private/types.h
include/public/osqp_api_constants.h
include/public/osqp_api_types.h
src/auxil.c
src/lin_sys.c
src/util.c
tests/basic_qp/test_basic_qp.h
tests/basic_qp2/test_basic_qp2.h
tests/non_cvx/test_non_cvx.h
tests/solve_linsys/test_solve_linsys.h
tests/update_matrices/test_update_matrices.h

This adds an `OSQP_` prefix to the constants/types/variables for identifying the linear solver to namespace them into OSQP and prevent possible conflicts with other software that might have similar defines.
I also shuffled around the order of the enum to make the unknown solver position 0, since previously it was at 99, and the status printing would try to index into an array with that value (so it would index into position 99 of a 2 element array). Putting it at position 0 allows for future expansion still, and puts it into a nice indexable position.

Prefix linear solver constants with OSQP to prevent clashes

---

algebra/_common/csc_math.c
algebra/_common/kkt.c
algebra/_common/kkt.h
algebra/default/lin_sys/direct/qdldl_interface.c
algebra/default/lin_sys/direct/qdldl_interface.h
include/types.h
src/osqp_api.c
tests/update_matrices/generate_problem.py
tests/update_matrices/test_update_matrices.h
tests/utils/codegen_utils.py

Implements support for partial updates to P and A matrices.
NB: untested because I think unit tests will require a modification to the python testing scripts to support export of c_int arrays that are required for indicating which elements to update.
Edit : I think it would also be a good idea to write one or more extra unit tests so that we can test 1) partial update of A and/or P and 2) full update of A and/or P.  This matters for P in particular because it is implemented two different ways.

partial data matrix updates

---

.github/workflows/main.yml
algebra/mkl/lin_sys/direct/pardiso_interface.c
algebra/mkl/lin_sys/direct/pardiso_interface.h
src/osqp_api.c

Since the signature of `update_linsys_solver_matrices` has changed, compilation with `-DALGEBRA=mkl` was failing. I looked at the recent changes in the `qdldl` case and am mirroring the changes here for the mkl interface. @goulart-paul - perhaps you can take a look and see if I missed something?
Also, for `-DEMBEDDED=2`, compilation was failing due to `NULL` being undefined. I've replaced those instances with `OSQP_NULL`. @imciner2 - is `0` is a better replacement here?

some interface fixes for update_matrices (for mkl algebra)

---

algebra/cuda/lin_sys/indirect/cuda_pcg_interface.cu

This was confusing to me at first, since it appeared that no matrices were actually being updated in the CUDA solver by just reading the function. So lets document what actually happens here to prevent this confusion.

Add comment to CUDA explaining matrix/vector update function

---

algebra/_common/kkt.c

not using for loop initial declarations (C99 only).
This error was reported inside the Docker containers used by BinaryBuilder for the Julia wrapper.

not using for loop initial declarations (C99 only)

---

.github/workflows/cmake-install.yaml
.github/workflows/main-cuda.yml
.github/workflows/main.yml
CMakeLists.txt

This PR does more CMake cleanup and contains the following things:
* Make notifications of automatic changes to build options due to other options into warnings so that it is more obvious to the user that something has changed from what is the default/specified by them.
* Migrate the testing/code coverage build options to be dependent options and rename them to prefix them.

CMake improvements

---

CMakeLists.txt

By appending the algebra type to the soname, the users can then ship multiple shared libraries next to eachother, each with a different algebra backend.
If the user specified the CMake flag `-DOSQP_LIB_SUFFIX_ALGEBRA=ON`, it will create libraries that look like the following:
For the default algebra:
```
$ objdump -x libosqp-builtin.so | grep SONAME
SONAME               libosqp-builtin.so
$ ls build/out
/home/b63738im/dev/optimization/osqp/c_code/build/out
Permissions Size User     Date Modified Git Name
.rwxrwxr-x@ 139k b63738im  5 Jul 14:59   -I libosqp-builtin.so
.rw-rw-r--@ 231k b63738im  5 Jul 14:59   -I libosqpstatic-builtin.a
.rwxrwxr-x@ 127k b63738im  5 Jul 14:59   -I osqp_codegen_demo
.rwxrwxr-x@ 127k b63738im  5 Jul 14:59   -I osqp_demo
```
For MKL:
```
$ objdump -x …
```

Support appending the algebra type to the library name

---

CMakeLists.txt

This now allows the user to specify more information/context for the library (such as adding float type, etc) instead of relying on automatically appending things. This provides more freedom.

Make the lib suffix more generic

---

.github/workflows/coverage.yaml
.github/workflows/embedded.yaml
.github/workflows/main.yml
.github/workflows/mkl.yaml

Instead of always installing MKL on the CI job, only install it in the ones that use the MKL algebra. This allows for the non-MKL jobs to continue even if there are issues installing it from conda.

Refactor CI jobs and test more combinations

---

CMakeLists.txt
algebra/cuda/CMakeLists.txt
algebra/mkl/CMakeLists.txt
algebra/mkl/algebra_libs.c
tests/CMakeLists.txt

Even on Linux we need to tell the shared library it has a dependency on MKL, otherwise the dynamic loader can have issues with undefined symbols because it doesn't know to load the MKL library. I have also cleaned up the linking so now the algebras define the libraries in a similar way to the include directories, removing the need for all the conditionals in the CMake code (and making the algebras more self contained).

Clean up algebra linking and always link against MKL

---

algebra/cuda/algebra_libs.cu
algebra/default/algebra_libs.c
algebra/mkl/algebra_libs.c
examples/osqp_demo.c
include/private/lin_alg.h
include/public/osqp_api_constants.h
include/public/osqp_api_functions.h
src/auxil.c
src/codegen.c
src/osqp_api.c
tests/CMakeLists.txt
tests/solve_linsys/test_solve_linsys.h

Adding a function to query the capabilities of the solver allows the user code/interfaces to query the solver for what it supports instead of having to hard-code specific information. This also allows the unit test suite to use this information to choose which linear system solvers to test automatically (with no need for define statements in the testing code).
I also abstracted the default linsys into the algebra, so now a new custom algebra a user develops can choose what solver to use without having to modify the actual solver functions.
@vineetbansal Once this is merged and you merge the develop branch into your derivative branch, you should add a new capability for derivative computation (since that will only be available on the builtin algebra at first).

Add function to query capabilities of the current library and abstract linear solver information

---

CMakeLists.txt

The `CMAKE_CUDA_ARCHITECTURES` variable requires at least CMake 3.18, so that needs to be our new minimum version to support setting the GPU architecture correctly (otherwise the CUDA build using double precision will fail because it is using a compute capability less than 6).
@vineetbansal I am not sure what CMake version is present in the Python build system you use, but this is a bump by only 2 minor versions (from 3.16 to 3.18). For the Julia build system, I had to update CMake for this since it was 3.17 (which is how I detected these variables weren't working to start with).

Raise minimum CMake version to 3.18

---

algebra/default/CMakeLists.txt
algebra/default/lin_sys/direct/qdldl_codegen_types.h.in
algebra/default/lin_sys/direct/qdldl_interface.c

Update the QDLDL version to the recently released version, and make it so that we only enable the object library target and not the shared/static libraries or the demo executable (since OSQP only needs the objects).

Update QDLDL to most recent upstream version

---

include/public/osqp_api_constants.h

I'm starting to incorporate supported capabilities in the python wrapper so as to better handle unsupported calls at runtime. I noticed that this renaming needs to happen for to avoid naming conflicts when compiling in the wrapper (since there's an `osqp_capabilities` api function already).
There seems to be no place in the `osqp` codebase itself where this renaming affects anything though.

Renamed osqp_capabilities enum to osqp_capabilities_type

---

algebra/builtin/algebra_libs.c
algebra/cuda/algebra_libs.cu
algebra/mkl/algebra_libs.c
examples/osqp_demo.c
include/public/osqp_api_constants.h
src/auxil.c
src/osqp_api.c
tests/utils/test_utils.cpp

I made a spelling mistake in the original implementation of the capability definitions, so this fixes it in all places now.

Fix spelling errors in capability defines

---

.github/workflows/precommit.yml
.pre-commit-config.yaml

A simple `pre-commit` starter configuration that currently checks for `yml` errors. We have a few `yml` files in this repo, and all currently pass the checks.
Use `pre-commit install` when in the `osqp` checkout folder to enable automated checks. For the CI, installing `pre-commit` through `conda` from the `conda-forge` channel seems to me to be a reasonable option. For local development when you don't want to use `conda` unnecessarily, I see that Ubuntu has a `apt install pre-commit` available. Other distros might have it too.
I'll add some python-related hooks in a future PR. C-related hooks seem to be at:
https://github.com/pocc/pre-commit-hooks
No modifications to the new gh-workflow file should be needed as we add more hooks to `.pre-commit-config.yaml` in the root folder.

Pre-commit

---

.github/workflows/docs.yml

This pair of steps (which **have** to run in the same workflow action as the main documentation), check out the `develop-1.0` branch of the repo, and build its documentation in a `develop-1.0` folder inside the current `docs` folder on the target `gh-pages` branch. I've tested this workflow in another repo and it seems to work well (and is the only way to do this AFAIK).
If all goes well, we should see, in addition to:
https://osqp.org/docs/
a parallel link:
https://osqp.org/docs/develop-1.0

Building docs for develop-1.0 in a subfolder

---

algebra/cuda/CMakeLists.txt

This adds a new option `OSQP_CUDA_STATIC_LINKAGE` that will statically link against the CUDA numerical libraries, meaning all CUDA libraries are now statically linked. This removes the need for a CUDA runtime on the computer that runs the library.

Allow CUDA to be fully statically linked

---

.github/workflows/coverage.yaml
.github/workflows/main-cuda.yml
.github/workflows/main.yml
.github/workflows/mkl.yaml

Instead of individually calling the tester, just use the ctest wrapper to call all the tests. Before this change we were skipping the linear algebra tests because they are now a separate tester executable, so with this change we restore the linear algebra tests.

CI: Run all tests compiled for a configuration

---

algebra/builtin/vector.c
algebra/cuda/vector.cu
algebra/mkl/blas_helpers.h
algebra/mkl/vector.c
include/private/algebra_vector.h
include/public/osqp_api_constants.h
src/osqp_api.c
src/polish.c
src/scaling.c
src/util.c
tests/basic_lp/test_basic_lp.cpp
tests/basic_qp2/test_basic_qp2.cpp
tests/lin_alg/generate_problem.py
tests/lin_alg/testcases/test_vector_math_ops.cpp
tests/no_active_set/test_no_active_set.cpp
tests/unconstrained/test_unconstrained.cpp

Polishing really only makes logical sense when there is an active set to polish against, so to prevent issues with the linear algebra when the A matrix is 0, just don't polish the solution if there is no active set. This is shown to the user through a notification and a new return status for the solution polishing variable:
```
-----------------------------------------------------------------
OSQP v0.0.0  -  Operator Splitting QP Solver
(c) Bartolomeo Stellato,  Goran Banjac
University of Oxford  -  Stanford University 2021
-----------------------------------------------------------------
problem:  variables n = 5, constraints m = 0
nnz(P) + nnz(A) = 5
settings: algebra = Built-in,
linear system solver = QDLDL v0.1.6,
eps_abs = 1.0e-05, eps_rel = 1.0e-05,
eps_prim_inf = 1.0e-04, …
```

Skip polishing when there is no active set detected

---

examples/osqp_codegen_demo.c
include/public/osqp_api_functions.h
src/osqp_api.c
tests/codegen/test_codegen.cpp

This allows for user code to have a way to initialize all fields of the struct, and be safe against possible future changes, such as adding fields to the struct.
@vineetbansal this should now be used in the interfaces to allocate default settings in a safe manner.

Add function to populate fields of OSQPCodegenDefines struct

---

algebra/_common/csc_math.c
algebra/_common/csc_math.h
algebra/_common/csc_utils.c
algebra/_common/csc_utils.h
algebra/_common/lin_sys/qdldl/qdldl_interface.c
algebra/_common/lin_sys/qdldl/qdldl_interface.h
algebra/_common/reduced_kkt.c
algebra/_common/reduced_kkt.h
algebra/builtin/CMakeLists.txt
algebra/builtin/matrix.c
algebra/cuda/lin_sys/indirect/cuda_pcg.cu
algebra/cuda/lin_sys/indirect/cuda_pcg_interface.cu
algebra/cuda/lin_sys/indirect/cuda_pcg_interface.h
algebra/mkl/CMakeLists.txt
algebra/mkl/algebra_libs.c
algebra/mkl/lin_sys/direct/pardiso_interface.c
algebra/mkl/lin_sys/direct/pardiso_interface.h
algebra/mkl/lin_sys/indirect/mkl-cg_interface.c
algebra/mkl/lin_sys/indirect/mkl-cg_interface.h
algebra/mkl/matrix.c
include/private/algebra_matrix.h
include/private/types.h
include/public/osqp_api_constants.h
include/public/osqp_api_types.h
src/codegen.c
src/osqp_api.c
src/util.c
tests/lin_alg/generate_problem.py
tests/lin_alg/test_matrix.cpp

This PR implements a diagonal (Jacobi) preconditioner for the MKL CG method. It takes a slightly different approach to doing the computation than the CUDA version does, with the main difference being there is no more conditional computation of parts of the preconditioner based on what parts were updated. This makes more sense since the only part that was really being saved was the extraction of the P matrix diagonal, since changing either rho or A would result in the same A'*D(rho)*A computation being done. This is done in a way that is still agnostic to the algebra backend, so it can theoretically be moved into a common routine when we get a CG method for the builtin algebras.
I have also added a new setting `cg_precond` for choosing the preconditioner to use, and it currently only has …

Add diagonal preconditioner to MKL CG

---

algebra/cuda/matrix.cu
algebra/cuda/src/cuda_csr.cu
algebra/cuda/src/cuda_lin_alg.cu

Some versions of cuSPARSE have problems with creating dense vectors with length 0 (they say it is an invalid input) and sparse matrices with any dimension of 0 length, so we need to avoid creating them. Instead, don't create them and just never perform the operations if there are no values in the matrices.
Hopefully this will fix the assertions we are seeing with the CUDA CI. (I can't test that locally because I haven't been able to trigger those on my machine, only on the CI machine).

CUDA: Don't allow creating cusparse matrices with a 0 dimension

---

algebra/cuda/include/cuda_lin_alg.h
algebra/cuda/src/cuda_lin_alg.cu
algebra/cuda/vector.cu

The CUDA computation of the vector 1 norm was never fully changed from being a mean computation to just being the absolute sum, so the linalg tests were failing the vector 1 norm tests.

Fix CUDA vector 1 norm computation

---

lin_sys/direct/pardiso/pardiso_interface.c
lin_sys/direct/pardiso/pardiso_loader.c
lin_sys/direct/pardiso/pardiso_loader.h

The R interface required these prototype fixes (among a few others) as CRAN enables prototype checks.  Reference: https://discourse.llvm.org/t/rfc-enabling-wstrict-prototypes-by-default-in-c/60521/20
The fixes here are very trivial.

Prototype fixes for pardiso

---

.github/workflows/main.yml

To see if its a macos-12 issue

Running CI on macos-11 + macos-latest

---

.github/workflows/check-links.yaml

This adds a simple workflow that will run at 2am everyday to test all the links on the OSQP website (both internal links and external links) to ensure they are valid. It operates by crawling the hosted website instead of our local copy, so we can get in-situ results and it can check both the stable and develop-1.0 docs as well, hopefully.
I need to push this to the master branch directly to allow the scheduled workflow to run properly (scheduled workflows only operate on the main/default branch).
Fixes https://github.com/osqp/osqp/issues/334

Add workflow to automatically check website links

---

.github/workflows/cmake-install.yaml
.github/workflows/codegen.yaml
.github/workflows/coverage.yaml
.github/workflows/docs.yml
.github/workflows/embedded.yaml
.github/workflows/main-cuda.yml
.github/workflows/main.yml
.github/workflows/mkl.yaml
.github/workflows/precommit.yml
.github/workflows/release.yml

GitHub has deprecated actions built on node 12 for their shared runners, so it now triggers warnings on every pipeline they are used. actions/checkout supports node 16 on v3, so bump our version from v2 to v3.
These deprecation warnings can be seen in run https://github.com/osqp/osqp/actions/runs/4554774592.

Bump version of checkout action to support node 16 by default

---

include/public/osqp_api_constants.h
include/public/osqp_api_functions.h
src/error.c
src/osqp_api.c

To preserve compatibility across different library versions compiled with different algebra backends, don't actually remove the codegen and derivative parts from the public API when they aren't implemented. Instead, return an error code saying the functions aren't implemented.
This way, any program compiled with a non-embedded OSQP version can be used with a static/shared library version from any backend without having to recompile or make any code changes.

Don't change the external API for codegen and derivatives

---

algebra/mkl/blas_helpers.h
algebra/mkl/vector.c
include/private/algebra_vector.h

Calling the Vector Math functions should provide more performance on some systems compared to hand-rolled loops. This isn't always true however, so we can't just replace everything. For instance, replacing a single for loop with two VML calls (such as for the elementwise bounding) might actually be more inefficient than the loop.
Also switch over to using the cblas wrapper to simplify the calling code (no need to pass pointers to integers, just pass the integers themselves).

Implement more MKL algebra vector functions using VML functions

---

algebra/cuda/lin_sys/indirect/cuda_pcg_interface.cu
src/osqp_api.c
tests/basic_lp/test_basic_lp.cpp
tests/basic_qp/test_basic_qp.cpp
tests/basic_qp2/test_basic_qp2.cpp
tests/codegen/test_codegen.cpp
tests/large_qp/test_large_qp.cpp
tests/lin_alg/lin_alg_tester.cpp
tests/no_active_set/test_no_active_set.cpp
tests/non_cvx/test_non_cvx.cpp
tests/osqp_tester.cpp
tests/osqp_tester.h
tests/primal_dual_infeasibility/test_primal_dual_infeasibility.cpp
tests/primal_infeasibility/test_primal_infeasibility.cpp
tests/unconstrained/test_unconstrained.cpp
tests/update_matrices/test_update_matrices.cpp
tests/utils/codegen_utils.py
tests/utils/test_utils.cpp

This PR adds an option for the test cases to run on a specified compute device number (specified through either a command line option or environment variable). It also implements a test fixture for the majority of test cases that contains all the data structures used, ensuring they are created and destroyed properly.

Allow tests to run on a specified compute device & modernize tests

---

algebra/mkl/CMakeLists.txt
algebra/mkl/algebra_libs.c

Turn the MKL linkage choice into a cache variable so that the user can specify it using a CMake command should they choose, but default to the single dynamic library version if nothing is given.
Fixes #296.

Allow user to override choice of MKL linkage

---

README.md
docs/index.rst
site/_config.yml
site/_includes/navbar.html

We have now switched to GitHub discussions as the primary Q&A forum, so direct users there in the documentation.

Replace references to discourse with GitHub discussions

---

algebra/_common/lin_sys/qdldl/qdldl_interface.c
algebra/_common/lin_sys/qdldl/qdldl_interface.h
algebra/cuda/include/cuda_wrapper.h
algebra/cuda/lin_sys/indirect/cuda_pcg.cu
algebra/cuda/src/cuda_csr.cu
algebra/cuda/src/cuda_lin_alg.cu
src/derivative.c

There were several issues in the code that caused errors when building the code in the Julia BinaryBuilder environment. The fixes are:
* Fix C90 compatibility: Don't define variables in for loop statements
* Fix compatibility with CUDA <11.2 (the name of the SPMV operation changed, and the one used in the code was only introduced in 11.2, so to allow building on 11.0 select the operation name based on the library version).
This also contains two minor fixes to the definition and calling of the adjoint derivative linear solver function.

Fix several issues that block building Julia wrappers

---

src/auxil.c

There was an incorrect and statement that should have been an or in the check on conjugate gradient fraction.

Replaced incorrect and statement with or

---

algebra/_common/kkt.c
algebra/_common/lin_sys/qdldl/qdldl_interface.c
algebra/_common/lin_sys/qdldl/qdldl_interface.h
algebra/builtin/algebra_libs.c
algebra/mkl/algebra_libs.c
algebra/mkl/lin_sys/direct/pardiso_interface.c
algebra/mkl/lin_sys/indirect/mkl-cg_interface.c
examples/osqp_codegen_demo.c
include/private/codegen.h
include/private/printing.h
include/private/util.h
src/auxil.c
src/codegen.c
src/error.c
src/osqp_api.c
src/scaling.c

Fix various warnings found when building with GCC `-Wall` flag.
Main changes are:
* Removing unused variables
* Modifying the format string used to write the integer based on the current `OSQPInt` type to make sure values are always representable

Fix build warnings

---

src/codegen.c

Fix a copy-paste error in the codegen header writing code.

Fix wrong flag check in codegen define writing

---

CMakePresets.json

These presets can be used with CMake 3.21+ to define specific build types, making it easier to select builds (such as debug builds for non-builtin algebras with tests).
example workflow:
```
cmake --preset mkl-debug
cmake --build build.debug.mkl/
ctest --test-dir build.debug.mkl/
```

Introduce CMake presets to make compilation easier

---

include/private/polish.h
src/osqp_api.c
src/polish.c

The polishing routines were allocating memory for vector and matrices and then never checking that the allocation succeeded. This PR fixes the polishing code to always check for successful memory allocation, and report the errors to the main polish routine if any occur.
(Memory use errors were flagged by running PVS-Studio on the code).

Improve error handling in polishing routines

---

algebra/_common/csc_utils.c
algebra/_common/lin_sys/qdldl/qdldl_interface.c
algebra/mkl/lin_sys/indirect/mkl-cg_interface.c

This fixes several potential memory leaks, and also cleans up the memory handling inside the QDLDL adjoint solver routine to ensure all allocations are checked and the allocations are unwound in reverse order if any errors occur.

Fix memory leaks and error handling in QDLDL adjoint linear solver

---

docs/interfaces/index.rst
docs/solver/index.rst

There are now a few community-developed implementations of the ADMM algorithm used by OSQP, so lets add a small table on the algorithm description page listing them and providing links to them.
What is written:
cc @loehndorf, this adds the jOSQP implementation into our documentation website.

Add list of community-developed implementations of our ADMM algorithm

---

CMakeLists.txt

On Windows, the LIBRARY_OUTPUT_NAME is not actually used for the DLL, since it is stored into the runtime location, so just make the basename for all items have the proper suffix.
This was found when doing a build of OSQP for the Julia JLL library.

Ensure shared library uses the suffix on all platforms

---

.github/workflows/mkl.yaml

The Windows Intel OpenMP import library is contained inside a different Conda package than the OpenMP runtime library, so we need to install the other package to get CMake to properly find and link against OpenMP.

[CI] Add additional dependency to the Windows CI to get OpenMP import library

---

.github/workflows/dependabot.yaml

Lets try this to keep on top of the GitHub actions versions, since we are having some deprecation warnings for actions in pipelines right now.

Enable dependabot on GitHub actions workflows

---

.github/workflows/coverage.yaml
.github/workflows/main-cuda.yml
.github/workflows/main.yml
.github/workflows/mkl.yaml
.github/workflows/release.yml
tests/testenv.yml

This unifies all our testing dependencies into a single environment definition that we can then include in every workflow that needs it, making pinning versions and keeping the workflows updated easier.

Switch to using a dedicated conda test environment for ghactions

---

.github/workflows/codeql.yml

The default CodeQL configuration is more conservative checks that only focus on security. There are also checks that can test for code quality, so lets enable those and see how it works.

Run more CodeQL checks to test code quality

---

.github/workflows/algebra-mkl.yaml

GitHub has upgraded the latest macOS runners to use macOS 14 now, and in the process also changed to using M1 instead of x86 (since macOS 14 is only available on M1). MKL does not support M1, so we must keep it on x86 by pinning the image to macos-13.

Pin MKL macOS CI to macOS 13 to get x86 runners

---

tests/testenv.yml

SciPy 1.13.0 fixed the transposed sparse matrix generation in https://github.com/scipy/scipy/pull/20314, so we can just exclude the 1.12 version to let newer SciPy versions be used as well.

Allow newer SciPy versions

---

.github/workflows/algebra-mkl.yaml
.github/workflows/coverage.yaml

The Intel conda repos changed locations, so now we must install using the full Intel URL instead of a specific anaconda channel. Additionally, we only need MKL when doing MKL tests in coverage, it is extraneous for the other backends and doesn't need to be installed.

Fix the CI involving MKL

---

docs/interfaces/status_values.rst

The existing link to the file where constants were defined was broken. Previously it pointed to `include/constants.h` but it should be pointing to `include/public/osqp_api_constants.h`.

Fixed broken link in documentation

---

docs/get_started/python.rst
docs/index.rst

Previously the python build instructions did not work. I assume the build process for the python wrapper changed at some point, but the documentation was not updated.

Fixed hyperlink on home page and python build instructions

---

algebra/_common/lin_sys/qdldl/qdldl.cmake
algebra/builtin/CMakeLists.txt

The FetchContent_Populate method was deprecated, so modify to use the MakeAvailable method, which requires a slightly different method of working (it automatically adds the subdirectory if it has the CMakeLists.txt present).
Also change QDLDL to be placed into the build directory, letting each build have an isolated copy of it.

Update to QDLDL 0.1.8 and update how we include it

---

include/public/osqp_api_functions.h

The `OSQP_API` annotation (used to ensure that functions are properly exported in Windows shared library) was missing from several public functions in `osqp_api_functions.h`. This PR adds the annotation to the functions that were missing it.
Without this, builds linking shared builds of OSQP could fail with errors like:
~~~
compilation_unit_using_osqp.cpp.obj : error LNK2019: unresolved external symbol OSQPCscMatrix_new referenced in function function_using_osqp
compilation_unit_using_osqp.cpp.obj : error LNK2019: unresolved external symbol OSQPCscMatrix_free referenced in function function_using_osqp
~~~

Add missing OSQP_API annotations in osqp_api_functions.h
